spring.application.name=connect-sphere
spring.profiles.active=dev

#server port 
server.port=8080



#jpa/hibernate 
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate

#flyway for migration
spring.flyway.enabled=true



