#lazy-init
spring.main.lazy-initialization=true

#jdbc driver for db
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/csphere
spring.datasource.username=postgres
spring.datasource.password=root



